name: Build React
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build React
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '22.0.0'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm install

      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
